console.log("Hello")
document.write("Hey Its Talha")
//alert("Run niggaaa")
let num = prompt("Enter a number : ")
let num1 = prompt("Enter a number : ")
num = parseInt(num,10)
num1 = parseInt(num1,10)
let sum = num+num1
alert("Sum is : "+sum)
document.write("<br/>Sum of entered number : " + sum)
let s
s = prompt("Your name : ")
alert("My name is " + s)
document.write("<br/>Entered name is : " + s.toUpperCase())
document.write("<br/>Entered name after slice : " + s.slice(0, 5))
document.write(`<br/>This is written to test the String Template by ${s} himself`)
console.log(`This is written to test the String Template by ${s} himself`)